# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "cherry"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

defaultThemeColor = "#FFFFFF"
